### ISSUE TITLE
sdk编译不过？lib冲突

### ISSUE THREAD

**Issue by yuxinfeng** [MeizuAppCenter/MzAppCenterSdkDemo#3]
在ubuntu下编译魅族sdk
/home/yuxinfeng/PRIS/app/src/debug/AndroidManifest.xml:10:5-12:41 Error:
        uses-sdk:minSdkVersion 14 cannot be smaller than version 18 declared in library [:MzUsageStats-3.2.0:] /home/yuxinfeng/.gradle/caches/transforms-1/files-1.1/MzUsageStats-3.2.0.aar/f6c0fdac91c27acc9277cb0be761e968/AndroidManifest.xml as the library might be using APIs not available in 14
        Suggestion: use a compatible library with a minSdk of at most 14,
                or increase this project's minSdk version to at least 18,
                or use tools:overrideLibrary="com.meizu.statsapp.v3" to force usage (may lead to runtime failures)

有兼容性问题，麻烦看一下？（奇怪的是在mac下编译没问题）

**Comment by shawnlinboy** [comment]
尝试在 app 模块的 `AndroidManifest.xml` 配置 `tools:overrideLibrary="com.meizu.statsapp.v3" `，然后执行  `./gradlew clean assemRelea`
