### ISSUE TITLE
正式签名打包，一调用支付就报错

### ISSUE THREAD

**Issue by briskemen** [MeizuAppCenter/MzAppCenterSdkDemo#4]
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter tradeNo

**Comment by shawnlinboy** [comment]
您好，请单步调试一下构造 `Payinfo` 对象时 `tradeNo` 的传值情况。

**Comment by briskemen** [comment]
debug模式下，调用没问题。签名发包再测试就发现了。然后又把kotlin插件依赖上，再打包，发现还是不行。

**Comment by shawnlinboy** [comment]
release 包，不要混淆，调试一下，看`tradeNo `传的什么。

**Comment by briskemen** [comment]
找到原因了。是本地一个实体bean没加混淆导致解析传值tradno出错。感谢帮助，提供了一大思路。
