### ISSUE TITLE
demo里面的picasso版本与你们最新的aar冲突。必须得依赖下面最新的版本

### ISSUE THREAD

**Issue by briskemen** [MeizuAppCenter/MzAppCenterSdkDemo#5]
implementation 'com.squareup.picasso:picasso:2.71828'

**Comment by shawnlinboy** [comment]
Demo 依赖的库不一定是最新的。

最新的库下载地址：https://github.com/MeizuAppCenter/MzAppCenterSdkDemo/releases
最新的文档：https://github.com/MeizuAppCenter/MzAppCenterSdkDemo
