### ISSUE TITLE
建议改成在线引用的方式

### ISSUE THREAD

**Issue by lany192** [MeizuAppCenter/MzAppCenterSdkDemo#6]
建议将这些aar包上传到公有的仓库或者是你们搭建的仓库中，方便开发者引用和升级。

**Comment by shawnlinboy** [comment]
这是一个非常棒的建议，我们之前跟 IT 部门的同事也提过，但是公司目前尚未有对外的 maven 仓库，所以目前还只能采用这种本地 aar 的形式，抱歉。
