### ISSUE TITLE
library-release.aar 与alipaySdk-20180403.jar的冲突问题

### ISSUE THREAD

**Issue by bandaotiehhe** [MeizuAppCenter/MzAppCenterSdkDemo#7]
你好。

在魅族联运SDK2.0的集成中，我发现library-release.aar与我们app需要使用的alipaySdk-20180403.jar含有相同的文件，导致打包编译失败。（alipaySdk用于app内购买实物）

而在联运SDK1.0中则不存在这个问题，这是否意味着在集成2.0以后，app将不再能使用alipaySdk？

以下是部分错误信息：

Duplicate class com.alipay.a.a.a found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.b found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.c found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.d found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.e found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.f found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.g found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.h found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.i found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.j found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.k found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.a.l found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)
  Duplicate class com.alipay.a.b.a found in modules alipaySdk-20180403.jar (alipaySdk-20180403.jar) and jetified-library-release-runtime.jar (library-release.aar)

**Comment by shawnlinboy** [comment]
`library-release.aar` 确实包含了 `alipaySDK`的一个版本，该版本如下图所示：

![image](https://user-images.githubusercontent.com/3414771/88752290-25525200-d18c-11ea-989a-fd705eac2142.png)

作为建议，请先尝试删除您的项目中的 `alipaySdk-20180403.jar`，看是否可以通过编译，如果删除后依旧有问题，或必须保留，请回复跟进此 issue 以便我们提供后续处理。

**Comment by bandaotiehhe** [comment]
> `library-release.aar`确实包含了`alipaySDK`一个版本，该版本如下图所示：
> 
> ![图片](https://user-images.githubusercontent.com/3414771/88752290-25525200-d18c-11ea-989a-fd705eac2142.png)
> 
> 作为建议，请先尝试删除您的项目中的`alipaySdk-20180403.jar`，看是否可以通过编译，如果删除后依旧有问题，或必须保留，请回复跟进此问题刹车我们提供后续处理。

你好，删除后可以编译通过，但这个alipaySdk-20180403.jar对于我们app是必要的。

**Comment by shawnlinboy** [comment]
> > `library-release.aar`确实包含了`alipaySDK`一个版本，该版本如下图所示：
> > ![图片](https://user-images.githubusercontent.com/3414771/88752290-25525200-d18c-11ea-989a-fd705eac2142.png)
> > 作为建议，请先尝试删除您的项目中的`alipaySdk-20180403.jar`，看是否可以通过编译，如果删除后依旧有问题，或必须保留，请回复跟进此问题刹车我们提供后续处理。
> 
> 你好，删除后可以编译通过，但这个alipaySdk-20180403.jar对于我们app是必要的。

群内已给出方案。
